#!/usr/bin/env python3
"""Deploy a sky-forge-amazon project to AWS.

Usage:  python scripts/deploy.py <stage>
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, cast

# Make infra.* importable when run as a plain script from the project root.
_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import boto3  # noqa: E402

from infra.config_loader import load_config  # noqa: E402
from infra.config_schema import DeployConfig, LambdaBackend, Stage  # noqa: E402
from infra.secrets_bootstrap import bootstrap_secrets  # noqa: E402
from infra.stacks.frontend_construct import frontend_domain  # noqa: E402

_YAML = Path("deploy.yaml")


# --------------------------------------------------------------------------- #
# Testable pure functions                                                     #
# --------------------------------------------------------------------------- #


def validate_stage(stage: str) -> None:
    if stage not in ("prod", "dev"):
        raise SystemExit(f"Invalid stage {stage!r}. Must be 'prod' or 'dev'.")


def check_account(cfg: DeployConfig) -> None:
    """Verify current credentials match cfg.aws_account before any other AWS call."""
    sts: Any = boto3.client("sts")
    identity = sts.get_caller_identity()
    actual: str = identity["Account"]
    if actual != cfg.aws_account:
        raise SystemExit(
            f"Account mismatch: deploy.yaml specifies aws_account={cfg.aws_account!r}, "
            f"but current credentials are for account {actual!r}.\n"
            "Update aws_account in deploy.yaml or switch AWS credentials."
        )


def generate_config_js(api_url: str, stage: str, api_key: str | None = None) -> str:
    config: dict[str, str] = {"apiUrl": api_url, "stage": stage}
    if api_key is not None:
        config["apiKey"] = api_key
    payload = json.dumps(config, indent=2)
    return f"// Auto-generated by deploy.py — do not edit\nwindow.APP_CONFIG = {payload};\n"


def get_stack_outputs(stack_name: str, region: str) -> dict[str, str]:
    cf: Any = boto3.client("cloudformation", region_name=region)
    response = cf.describe_stacks(StackName=stack_name)
    return {o["OutputKey"]: o["OutputValue"] for o in response["Stacks"][0].get("Outputs", [])}


# --------------------------------------------------------------------------- #
# CDK invocation                                                              #
# --------------------------------------------------------------------------- #


def _cdk_exe() -> str:
    exe = shutil.which("cdk") or shutil.which("cdk.cmd")
    if not exe:
        raise SystemExit("cdk CLI not found in PATH. Install it with: npm install -g aws-cdk")
    return exe


def run_cdk(args: list[str]) -> None:
    cmd = [_cdk_exe(), *args]
    result = subprocess.run(cmd, shell=False)
    if result.returncode != 0:
        raise SystemExit(f"cdk {args[0]} exited with code {result.returncode}")


# --------------------------------------------------------------------------- #
# Main                                                                        #
# --------------------------------------------------------------------------- #


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("Usage: python scripts/deploy.py <stage>")

    stage_raw = sys.argv[1]
    validate_stage(stage_raw)
    stage = cast(Stage, stage_raw)

    cfg = load_config(_YAML, stage)
    check_account(cfg)

    print(f"\nBootstrapping secrets for {cfg.project}/{stage}...")
    bootstrap_secrets(cfg)

    api_url = f"https://api.{frontend_domain(cfg)}"
    frontend_src = Path(cfg.frontend.source_path)
    (frontend_src / "config.js").write_text(generate_config_js(api_url, stage))

    stack_name = f"{cfg.project}-{cfg.stage}"
    print(f"\nDeploying {stack_name}...")
    run_cdk(["deploy", stack_name, "--require-approval", "never"])

    print(f"\nFetching outputs for {stack_name}...")
    outputs = get_stack_outputs(stack_name, cfg.aws_region)

    frontend_url = outputs.get("FrontendUrl", f"https://{frontend_domain(cfg)}")
    api_url_out = outputs.get("ApiUrl", api_url)
    print(f"\nFrontendUrl: {frontend_url}")
    print(f"ApiUrl:      {api_url_out}")

    if cfg.security.api_key_required:
        key_id = outputs.get("ApiKeyId")
        if key_id:
            apigw: Any = boto3.client("apigateway", region_name=cfg.aws_region)
            key_resp = apigw.get_api_key(apiKey=key_id, includeValue=True)
            key_value: str = key_resp.get("value", "")
            (frontend_src / "config.js").write_text(
                generate_config_js(api_url, stage, api_key=key_value)
            )
            print(f"ApiKey:      {key_value}")
        else:
            print("ApiKey:      (ApiKeyId not found in stack outputs)")

    # EC2 note: CDK handles app zipping via s3_assets.Asset during deploy.
    # No manual zip step is needed in the deploy script.
    if not isinstance(cfg.backend, LambdaBackend):
        print(
            "\nNote: EC2 app code was packaged by CDK (s3_assets.Asset). "
            "The instance will re-bootstrap on next boot after this deploy "
            "because of the ASG replacing_update policy."
        )


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nAborted.")
        sys.exit(1)
